/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package td07.testeJTable;

import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;


/**
 *
 * @author Hugo
 */
public class DelForm extends javax.swing.JFrame{

    /**
     * Creates new form DelForm
     */
    //
    ElementoTableModel modelo;
    ArrayList vetAl = new ArrayList();
    
    private void initInterface(){
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try{
            String vetS[] = new String[] {"Símbolo", "Nome", "Num. Atômico", "Massa Atômica", "Num.de Períodos", "Família", ""} ; 
            String col [] = {"H"," Hidrogênio", "1"," 1.008"," 1"," 1","elements/h.png"};
            vetAl.add(col);
            String col2[] = {"He", "Hélio", "2", "4.003", "1", "18", "elements/he.png"};
            vetAl.add(col2);
            String col3[] = {"Li", "Lítio", "3", "6.941", "2", "1", "elements/li.png"};
            vetAl.add(col3);
            String col4[] = {"Be", "Berílio", "4"," 9.012", "2", "2", "elements/be.png"};
            vetAl.add(col4);
            String col5[] = {"B", "Boro", "5", "10.81", "2", "13", "elements/b.png"};
            vetAl.add(col5);
            String col6[] = {"C", "Carbono", "6", "12.01", "2", "14", "elements/c.png"};
            vetAl.add(col6);
            modelo = new ElementoTableModel(vetAl,vetS);
            tabela.setModel(modelo);
            
            TableColumn escondida = tabela.getColumnModel().getColumn(ElementoTableModel.ID_INDEX);
            escondida.setMaxWidth(2);
            escondida.setPreferredWidth(2);
            escondida.setMinWidth(2);
            tabela.repaint();
            setSize(630,520);
            setLocation(320, 120);
        }catch (NullPointerException e){
            
        }
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }
    public DelForm () {
        initComponents();
        initInterface();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_Excluir = new javax.swing.JButton();
        btn_Fechar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_Arquivo = new javax.swing.JMenu();
        itemmenu_AddElem = new javax.swing.JMenuItem();
        itemmenu_RemvElem = new javax.swing.JMenuItem();
        Separador = new javax.swing.JPopupMenu.Separator();
        itemmenu_Sair = new javax.swing.JMenuItem();
        menu_Ajuda = new javax.swing.JMenu();
        itemmenu_Conteudo = new javax.swing.JMenuItem();
        itemmenu_Sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listagem dos Elementos"));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.BorderLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Excluir);

        btn_Fechar.setText("Fechar");
        btn_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FecharActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Fechar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        menu_Arquivo.setText("Arquivo");

        itemmenu_AddElem.setText("Adicionar Elemento");
        menu_Arquivo.add(itemmenu_AddElem);

        itemmenu_RemvElem.setText("Remover Elemento");
        menu_Arquivo.add(itemmenu_RemvElem);
        menu_Arquivo.add(Separador);

        itemmenu_Sair.setText("Sair");
        itemmenu_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmenu_SairActionPerformed(evt);
            }
        });
        menu_Arquivo.add(itemmenu_Sair);

        jMenuBar1.add(menu_Arquivo);

        menu_Ajuda.setText("Ajuda");

        itemmenu_Conteudo.setText("Conteúdo");
        menu_Ajuda.add(itemmenu_Conteudo);

        itemmenu_Sobre.setText("Sobre");
        menu_Ajuda.add(itemmenu_Sobre);

        jMenuBar1.add(menu_Ajuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemmenu_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmenu_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itemmenu_SairActionPerformed

    private void btn_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_FecharActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        // TODO add your handling code here:
        try{
            
            int linha = tabela.getSelectedRow();
            
            String indice_escol = tabela.getValueAt(linha,modelo.ID_INDEX).toString();
            String num_atomic = tabela.getValueAt(linha,modelo.NUMERO_ATOMICO_INDEX).toString();
            
            modelo.removeRow(indice_escol,modelo.ID_INDEX);
            
            TableColumn outra = tabela.getColumnModel().getColumn(ElementoTableModel.ID_INDEX);
            outra.setMaxWidth(2);
            outra.setPreferredWidth(2);
            outra.setMinWidth(2);
            tabela.repaint();
            setSize(630,520);
            setLocation(320, 120);
            
            JOptionPane.showMessageDialog(null, "Removido com sucesso");
            
            btn_Excluir.grabFocus();
        }catch (ArrayIndexOutOfBoundsException e){
            
        }
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DelForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator Separador;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Fechar;
    private javax.swing.JMenuItem itemmenu_AddElem;
    private javax.swing.JMenuItem itemmenu_Conteudo;
    private javax.swing.JMenuItem itemmenu_RemvElem;
    private javax.swing.JMenuItem itemmenu_Sair;
    private javax.swing.JMenuItem itemmenu_Sobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu_Ajuda;
    private javax.swing.JMenu menu_Arquivo;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
